#!/bin/bash
#PBS -A project-ID
#PBS -q qexp
#PBS -l select=1:ncpus=36:mpiprocs=36:ompthreads=1
#PBS -l walltime=1:00:00
#PBS -N job_test
#PBS -j oe
#PBS -S /bin/bash

cd ${PBS_O_WORKDIR}
SCRDIR=/scratch/

mkdir -p $SCRDIR
cd $SCRDIR || exit
cp -f -r $PBS_O_WORKDIR/* .
ml purge
ml QuantumESPRESSO
ml intel
chmod +x ./run.sh

./run.sh >> log

exit
