#! /bin/bash

for i in {1..2}
do
for j in {1..7}
do
mkdir P_${i}_${j}
cp POSCAR_${i}_${j} ./P_${i}_${j}/POSCAR
cp KPOINTS ./P_${i}_${j}
cp POTCAR ./P_${i}_${j}
cp INCAR_std ./P_${i}_${j}/INCAR
cp vasp_jsub ./P_${i}_${j}/
sed -i "s/AA/$i/"  ./P_${i}_${j}/vasp_jsub
sed -i "s/BB/$j/"  ./P_${i}_${j}/vasp_jsub
cp vasp_0 ./P_${i}_${j}/
cd ./P_${i}_${j}/
qsub vasp_jsub
cd ..
done
done

