#!/bin/bash

inputlmpaelas=in.aelas    # input file name for LAMMPS to run AELAS

inputlmpmaelas=in.maelas    # input file name for LAMMPS to run MAELAS

exelmp=lmp_serial  # name of the executable file for LAMMPS



############# AELAS (we first run AELAS to generate the ELADAT file)

./gen_poscar_aelas.sh


for i in {1..3}

do

for j in {1..13}
 
do
	

cp ${inputlmpaelas} in.lmp_0


sed -i "s/AA/$i/"  ./in.lmp_0
sed -i "s/BB/$j/"  ./in.lmp_0


${exelmp} < in.lmp_0 > results_aelas_${i}_${j}


ene=`grep "energy" energy_${i}_${j}.dat | awk '{print $2}'`


if [ $j -gt 9 ];
then
cp OSZICAR OSZICAR_0${i}_0${j}

sed -i "s/energy_lmp/$ene/"  ./OSZICAR_0${i}_0${j}

else
	
cp OSZICAR OSZICAR_0${i}_00${j}

sed -i "s/energy_lmp/$ene/"  ./OSZICAR_0${i}_00${j}
fi


done

done


AELAS -d


######### MAELAS 

./gen_poscar_maelas.sh


for i in {1..1}

do

for j in {1..7}

do


cp ${inputlmpmaelas} in.lmp_0


sed -i "s/AA/$i/"  ./in.lmp_0
sed -i "s/BB/$j/"  ./in.lmp_0


${exelmp} < in.lmp_0 > results_maelas_${i}_${j}


ene=`grep "energy" energy_${i}_${j}.dat | awk '{print $2}'`


cp OSZICAR OSZICAR_${i}_${j}_1

sed -i "s/energy_lmp/$ene/"  ./OSZICAR_${i}_${j}_1


done

done


maelas -mode 3 -d -s 0.01 -n 7 -b > output.dat 



